### ISSUE TITLE
[fastpages] Automated Upgrade

### ISSUE THREAD

**Issue by hamelsmu** [morganmcg1/ntentional#4]
Opening this issue will trigger GitHub Actions to fetch the lastest version of [fastpages](https://github.com/fastai/fastpages).  More information will be provided in forthcoming comments below.

I was reading your blog posts about Hugging face + fastai b/c it is something I am trying to figure out.  I noticed that you could upgrade your fastpages instance as I have fixed some bugs, so opening this issue as it will trigger a pull request.  

Thanks for the blog posts they are very helpful

**Comment by hamelsmu** [comment]
haha nice the error checking at least works.

**Comment by morganmcg1** [comment]
Sorry just seeing this now (1 month later!!). Let me know if theres anything HF + fastai related I can help with, seems like a lot of great stuff coming out on the forums in the past month

**Comment by hamelsmu** [comment]
What is HF ?

**Comment by morganmcg1** [comment]
sorry, HuggingFace!
